"""empty message

Revision ID: 1008d9b0fcd9
Revises: 
Create Date: 2023-10-14 11:55:39.312709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1008d9b0fcd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet',
    sa.Column('row_size', sa.Integer(), nullable=False),
    sa.Column('col_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('col_sindex',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('row_sindex',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell',
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('dtype', sa.String(length=8), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('row_sindex_id', sa.Uuid(), nullable=False),
    sa.Column('col_sindex_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['col_sindex_id'], ['col_sindex.id'], ),
    sa.ForeignKeyConstraint(['row_sindex_id'], ['row_sindex.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell')
    op.drop_table('row_sindex')
    op.drop_table('col_sindex')
    op.drop_table('sheet')
    # ### end Alembic commands ###
