"""empty message

Revision ID: 186e42a66fec
Revises: b9deb69b6f4e
Create Date: 2023-10-18 12:15:10.424903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '186e42a66fec'
down_revision: Union[str, None] = 'b9deb69b6f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('source_info_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'group', 'source', ['source_info_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'source_info_id')
    # ### end Alembic commands ###
