"""empty message

Revision ID: 416c09ffd3ed
Revises: cbddd923071f
Create Date: 2023-10-20 19:36:51.115944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '416c09ffd3ed'
down_revision: Union[str, None] = 'cbddd923071f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('plan_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_info_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_info_id'], ['source.id'], name='group_source_info_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_pkey')
    )
    # ### end Alembic commands ###
