"""empty message

Revision ID: 7ef26dc9ecab
Revises: ea7ce45c4955
Create Date: 2023-10-27 15:09:48.735746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7ef26dc9ecab'
down_revision: Union[str, None] = 'ea7ce45c4955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
                    sa.Column('key', sa.String(length=32), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subscriber',
                    sa.Column('key', sa.String(length=32), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('pubsub_association_table',
                    sa.Column('pub_id', sa.Uuid(), nullable=False),
                    sa.Column('sub_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['pub_id'], ['publisher.id'], ),
                    sa.ForeignKeyConstraint(['sub_id'], ['subscriber.id'], ),
                    sa.PrimaryKeyConstraint('pub_id', 'sub_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pubsub_association_table')
    op.drop_table('subscriber')
    op.drop_table('publisher')
    # ### end Alembic commands ###
