"""empty message

Revision ID: 881015474adb
Revises: 
Create Date: 2023-11-01 21:35:56.054069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881015474adb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber',
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('col_sindex',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('is_freeze', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pubsub_association_table',
    sa.Column('pub_id', sa.Uuid(), nullable=False),
    sa.Column('sub_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['pub_id'], ['publisher.id'], ),
    sa.ForeignKeyConstraint(['sub_id'], ['subscriber.id'], ),
    sa.PrimaryKeyConstraint('pub_id', 'sub_id')
    )
    op.create_table('report',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('freq', sa.String(length=16), nullable=False),
    sa.Column('plan_items', sa.JSON(), nullable=False),
    sa.Column('sheet_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('row_sindex',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('is_readonly', sa.Boolean(), nullable=False),
    sa.Column('is_freeze', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wire',
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sender', sa.Float(), nullable=False),
    sa.Column('receiver', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sub1', sa.String(length=1024), nullable=False),
    sa.Column('sub2', sa.String(length=1024), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell',
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('dtype', sa.String(length=8), nullable=False),
    sa.Column('background', sa.String(length=21), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('row_sindex_id', sa.Uuid(), nullable=False),
    sa.Column('col_sindex_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['col_sindex_id'], ['col_sindex.id'], ),
    sa.ForeignKeyConstraint(['row_sindex_id'], ['row_sindex.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell')
    op.drop_table('wire')
    op.drop_table('row_sindex')
    op.drop_table('report')
    op.drop_table('pubsub_association_table')
    op.drop_table('col_sindex')
    op.drop_table('subscriber')
    op.drop_table('source')
    op.drop_table('sheet')
    op.drop_table('publisher')
    # ### end Alembic commands ###
