"""empty message

Revision ID: 8bbe21d9e5ee
Revises: e93611b882a4
Create Date: 2023-10-27 16:05:32.062173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbe21d9e5ee'
down_revision: Union[str, None] = 'e93611b882a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('publisher_key_key', 'publisher', type_='unique')
    op.drop_constraint('subscriber_key_key', 'subscriber', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subscriber_key_key', 'subscriber', ['key'])
    op.create_unique_constraint('publisher_key_key', 'publisher', ['key'])
    # ### end Alembic commands ###
