"""empty message

Revision ID: b5cfc260c0ab
Revises: c00dc2f2db3a
Create Date: 2023-10-06 18:35:39.680146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5cfc260c0ab'
down_revision: Union[str, None] = 'c00dc2f2db3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('col_sindex',
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_uuid'], ['sheet.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('row_sindex',
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_uuid'], ['sheet.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('cell',
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('dtype', sa.String(length=8), nullable=False),
    sa.Column('sheet_uuid', sa.Uuid(), nullable=False),
    sa.Column('row_sindex_uuid', sa.Uuid(), nullable=False),
    sa.Column('col_sindex_uuid', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['col_sindex_uuid'], ['col_sindex.uuid'], ),
    sa.ForeignKeyConstraint(['row_sindex_uuid'], ['row_sindex.uuid'], ),
    sa.ForeignKeyConstraint(['sheet_uuid'], ['sheet.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('sindex')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sindex',
    sa.Column('direction', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sheet_uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sheet_uuid'], ['sheet.uuid'], name='sindex_sheet_uuid_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='sindex_pkey')
    )
    op.drop_table('cell')
    op.drop_table('row_sindex')
    op.drop_table('col_sindex')
    # ### end Alembic commands ###
