"""empty message

Revision ID: b9deb69b6f4e
Revises: c961fd5aa337
Create Date: 2023-10-18 11:38:12.530794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9deb69b6f4e'
down_revision: Union[str, None] = 'c961fd5aa337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.Column('plan_items', sa.JSON(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
