"""empty message

Revision ID: c00dc2f2db3a
Revises: cd029a364f55
Create Date: 2023-10-06 18:24:12.200216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c00dc2f2db3a'
down_revision: Union[str, None] = 'cd029a364f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sindex',
                    sa.Column('direction', sa.String(length=8), nullable=False),
                    sa.Column('position', sa.Integer(), nullable=False),
                    sa.Column('sheet_uuid', sa.Uuid(), nullable=False),
                    sa.Column('uuid', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['sheet_uuid'], ['sheet.uuid'], ),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sindex')
    # ### end Alembic commands ###
