"""empty message

Revision ID: c78060502975
Revises: 39d0e1a808aa
Create Date: 2023-11-06 12:28:20.994546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78060502975'
down_revision: Union[str, None] = '39d0e1a808aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cell', sa.Column('is_readonly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cell', 'is_readonly')
    # ### end Alembic commands ###
