"""empty message

Revision ID: cbddd923071f
Revises: 
Create Date: 2023-10-20 14:35:04.956687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbddd923071f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('periods', sa.JSON(), nullable=False),
    sa.Column('plan_items', sa.JSON(), nullable=False),
    sa.Column('sheet_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sheet',
    sa.Column('row_size', sa.Integer(), nullable=False),
    sa.Column('col_size', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('col_sindex',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('plan_items', sa.JSON(), nullable=False),
    sa.Column('source_info_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_info_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('row_sindex',
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wire',
    sa.Column('date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sender', sa.Float(), nullable=False),
    sa.Column('receiver', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sub1', sa.String(length=1024), nullable=False),
    sa.Column('sub2', sa.String(length=1024), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cell',
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('dtype', sa.String(length=8), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('row_sindex_id', sa.Uuid(), nullable=False),
    sa.Column('col_sindex_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['col_sindex_id'], ['col_sindex.id'], ),
    sa.ForeignKeyConstraint(['row_sindex_id'], ['row_sindex.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cell')
    op.drop_table('wire')
    op.drop_table('row_sindex')
    op.drop_table('group')
    op.drop_table('col_sindex')
    op.drop_table('source')
    op.drop_table('sheet')
    op.drop_table('report')
    # ### end Alembic commands ###
