"""empty message

Revision ID: cd029a364f55
Revises: afb88eab114d
Create Date: 2023-10-06 16:58:17.793413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cd029a364f55'
down_revision: Union[str, None] = 'afb88eab114d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sheet',
                    sa.Column('uuid', sa.Uuid(), nullable=False),
                    sa.Column('row_size', sa.Integer(), nullable=False),
                    sa.Column('col_size', sa.Integer(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sheet')
    # ### end Alembic commands ###
