"""empty message

Revision ID: cd8583b79152
Revises: 53c42d99ff24
Create Date: 2023-10-16 21:25:18.877877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cd8583b79152'
down_revision: Union[str, None] = '53c42d99ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.Column('source_id', sa.Uuid(), nullable=False),
                    sa.Column('sheet_id', sa.Uuid(), nullable=False),
                    sa.Column('plan_items', sa.JSON(), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['sheet_id'], ['sheet.id'], ),
                    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
