"""empty message

Revision ID: ea7ce45c4955
Revises: 8a89a052aa2f
Create Date: 2023-10-25 11:09:31.785115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7ce45c4955'
down_revision: Union[str, None] = '8a89a052aa2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet', 'row_size')
    op.drop_column('sheet', 'col_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet', sa.Column('col_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sheet', sa.Column('row_size', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
