"""empty message

Revision ID: f7ffcad8522e
Revises: ce4525a16183
Create Date: 2023-11-04 11:13:21.822420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ffcad8522e'
down_revision: Union[str, None] = 'ce4525a16183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula',
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('formula_key', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formula')
    # ### end Alembic commands ###
